name: Build Android APK

on:
  push:
    branches: [ main ]  # 确保和你提交修改的分支一致，一般是main或master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main  # 强制拉取main分支的最新代码

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'  # 固定稳定版Flutter
          channel: 'stable'

      - name: Clean & Get dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Build APK
        run: flutter build apk --release
